#!/usr/bin/env python3
"""
JavaScript/TypeScript test runner using Jest and nyc
Supports: generate, run, coverage, mutation, benchmark operations
"""

import argparse
import os
import sys
import subprocess
import json
import re
from pathlib import Path
from typing import Dict, List, Optional


def parse_js_functions(file_path: str) -> Dict:
    """Parse JavaScript/TypeScript file to extract function signatures."""
    path = Path(file_path)
    if not path.exists():
        return {"functions": [], "classes": []}
    
    content = path.read_text()
    
    functions = []
    classes = []
    
    # Match function declarations: function name(args) or const name = (args) =>
    func_patterns = [
        r'(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)',
        r'(?:export\s+)?const\s+(\w+)\s*=\s*(?:async\s+)?\(([^)]*)\)\s*=>',
        r'(?:export\s+)?(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s+)?function\s*\(([^)]*)\)',
    ]
    
    for pattern in func_patterns:
        for match in re.finditer(pattern, content):
            func_name = match.group(1)
            args = match.group(2).strip()
            
            # Skip private/internal
            if func_name.startswith("_"):
                continue
            
            functions.append({
                "name": func_name,
                "args": [a.strip() for a in args.split(",") if a.strip()] if args else [],
                "is_async": "async" in match.group(0)
            })
    
    # Match class declarations
    class_pattern = r'(?:export\s+)?class\s+(\w+)(?:\s+extends\s+\w+)?\s*\{'
    for match in re.finditer(class_pattern, content):
        class_name = match.group(1)
        
        # Find methods in class
        class_start = match.end()
        # Simple bracket matching to find class body
        brace_count = 1
        class_end = class_start
        for i, char in enumerate(content[class_start:]):
            if char == "{":
                brace_count += 1
            elif char == "}":
                brace_count -= 1
                if brace_count == 0:
                    class_end = class_start + i
                    break
        
        class_body = content[class_start:class_end]
        methods = []
        
        method_pattern = r'(?:async\s+)?(\w+)\s*\(([^)]*)\)\s*\{'
        for m in re.finditer(method_pattern, class_body):
            method_name = m.group(1)
            if not method_name.startswith("_") and method_name not in ["constructor", "get", "set"]:
                methods.append({
                    "name": method_name,
                    "args": [a.strip() for a in m.group(2).split(",") if a.strip()] if m.group(2) else []
                })
        
        classes.append({
            "name": class_name,
            "methods": methods
        })
    
    return {"functions": functions, "classes": classes}


def generate_jest_tests(file_path: str, output_path: Optional[str] = None) -> Dict:
    """Generate Jest test scaffolding for a JS/TS file."""
    path = Path(file_path)
    parsed = parse_js_functions(file_path)
    
    module_name = path.stem
    ext = path.suffix  # .js, .ts, .jsx, .tsx
    test_ext = ".test" + ext
    
    if output_path:
        output = Path(output_path)
        if output.is_dir():
            test_file_path = output / (module_name + test_ext)
        else:
            test_file_path = output
    else:
        test_file_path = path.parent / (module_name + test_ext)
    
    # Determine import style
    if ext in [".ts", ".tsx"]:
        import_line = f'import * as {module_name} from "./{module_name}";'
    else:
        import_line = f'const {module_name} = require("./{module_name}");'
    
    lines = [
        f'/**',
        f' * Tests for {path.name}',
        f' * Auto-generated by test-automation skill',
        f' */',
        f'',
        import_line,
        f'',
        f'describe("{module_name}", () => {{',
        f'  ',
    ]
    
    # Generate tests for functions
    for func in parsed.get("functions", []):
        func_name = func["name"]
        is_async = func.get("is_async", False)
        args = func.get("args", [])
        
        lines.extend([
            f'  describe("{func_name}", () => {{',
            f'    it("should work correctly", async () => {{',
            f'      // Arrange',
        ])
        
        if args:
            lines.append(f'      // TODO: Set up test inputs for: {", ".join(args)}')
        
        lines.extend([
            f'      ',
            f'      // Act',
        ])
        
        if is_async:
            lines.append(f'      const result = await {module_name}.{func_name}();')
        else:
            lines.append(f'      const result = {module_name}.{func_name}();')
        
        lines.extend([
            f'      ',
            f'      // Assert',
            f'      // TODO: Add appropriate assertions',
            f'      expect(result).toBeDefined();',
            f'    }});',
            f'  }});',
            f'  ',
        ])
    
    # Generate tests for classes
    for cls in parsed.get("classes", []):
        class_name = cls["name"]
        lines.extend([
            f'  describe("{class_name}", () => {{',
            f'    let instance;',
            f'    ',
            f'    beforeEach(() => {{',
            f'      instance = new {module_name}.{class_name}();',
            f'    }});',
            f'    ',
        ])
        
        for method in cls.get("methods", []):
            method_name = method["name"]
            lines.extend([
                f'    describe("{method_name}", () => {{',
                f'      it("should work correctly", () => {{',
                f'        // TODO: Implement test',
                f'        expect(instance.{method_name}).toBeDefined();',
                f'      }});',
                f'    }});',
                f'    ',
            ])
        
        lines.extend([
            f'  }});',
            f'  ',
        ])
    
    lines.extend([
        f'}});',
        f'',
    ])
    
    test_content = "\n".join(lines)
    test_file_path.write_text(test_content)
    
    return {
        "success": True,
        "test_file": str(test_file_path),
        "functions_found": len(parsed.get("functions", [])),
        "classes_found": len(parsed.get("classes", [])),
        "output": f"Generated test file: {test_file_path}\n{test_content}"
    }


def run_jest_tests(test_path: str, framework: str = "jest") -> Dict:
    """Run Jest tests and return results."""
    path = Path(test_path)
    
    # Find project root
    project_root = path
    while project_root.parent != project_root:
        if (project_root / "package.json").exists():
            break
        project_root = project_root.parent
    
    # Determine test runner command
    if framework == "vitest":
        cmd = ["npx", "vitest", "run", str(path), "--reporter=verbose"]
    elif framework == "mocha":
        cmd = ["npx", "mocha", str(path)]
    else:
        # Default to Jest
        cmd = ["npx", "jest", str(path), "--verbose"]
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=300,
            cwd=project_root
        )
        
        output = result.stdout + result.stderr
        
        # Parse Jest output
        passed = len(re.findall(r'✓|✔|PASS', output))
        failed = len(re.findall(r'✕|✖|FAIL', output))
        
        # Extract test suites info
        suites_match = re.search(r'Test Suites:\s+(\d+)\s+passed.*?,(\d+)\s+failed', output)
        tests_match = re.search(r'Tests:\s+(\d+)\s+passed.*?,(\d+)\s+failed', output)
        
        return {
            "success": result.returncode == 0,
            "exit_code": result.returncode,
            "passed": passed,
            "failed": failed,
            "output": output
        }
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "error": "Test execution timed out (5 minutes)",
            "output": ""
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "output": ""
        }


def run_coverage(source_path: str, framework: str = "jest") -> Dict:
    """Generate coverage report using nyc (Istanbul)."""
    path = Path(source_path)
    
    # Find project root
    project_root = path
    while project_root.parent != project_root:
        if (project_root / "package.json").exists():
            break
        project_root = project_root.parent
    
    try:
        # Run tests with coverage
        if framework == "vitest":
            cmd = ["npx", "vitest", "run", "--coverage", str(path)]
        else:
            cmd = ["npx", "jest", "--coverage", str(path)]
        
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=300,
            cwd=project_root
        )
        
        output = result.stdout + result.stderr
        
        # Parse coverage summary
        coverage_match = re.search(r'All files\s+\|\s+([\d.]+)', output)
        coverage_percent = float(coverage_match.group(1)) if coverage_match else 0
        
        # Try to get JSON coverage report
        coverage_json_path = project_root / "coverage" / "coverage-summary.json"
        coverage_data = {}
        if coverage_json_path.exists():
            try:
                coverage_data = json.loads(coverage_json_path.read_text())
            except:
                pass
        
        # Extract uncovered lines if available
        uncovered = {}
        lcov_path = project_root / "coverage" / "lcov-report" / "index.html"
        if lcov_path.exists():
            # Parse lcov report for missing lines
            pass  # Would need more complex parsing
        
        return {
            "success": True,
            "coverage_percent": round(coverage_percent, 2),
            "output": output,
            "coverage_data": coverage_data
        }
        
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "output": ""
        }


def run_mutation_test(file_path: str) -> Dict:
    """Run mutation testing using Stryker (if available)."""
    path = Path(file_path)
    
    project_root = path
    while project_root.parent != project_root:
        if (project_root / "package.json").exists():
            break
        project_root = project_root.parent
    
    # Check if Stryker is configured
    stryker_config = project_root / "stryker.config.json"
    has_stryker = stryker_config.exists()
    
    if not has_stryker:
        # Create basic Stryker config
        stryker_config.write_text(json.dumps({
            "$schema": "https://unpkg.com/@stryker-mutator/core/schema/stryker-schema.json",
            "packageManager": "npm",
            "reporters": ["html", "clear-text", "progress"],
            "testRunner": "jest",
            "coverageAnalysis": "perTest"
        }, indent=2))
    
    try:
        # Run Stryker
        result = subprocess.run(
            ["npx", "stryker", "run"],
            capture_output=True,
            text=True,
            timeout=600,
            cwd=project_root
        )
        
        output = result.stdout + result.stderr
        
        # Parse mutation score
        score_match = re.search(r'([\d.]+)%', output)
        mutation_score = float(score_match.group(1)) if score_match else 0
        
        return {
            "success": result.returncode == 0,
            "mutation_score": mutation_score,
            "output": output
        }
        
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "output": ""
        }


def run_benchmark(file_path: str) -> Dict:
    """Run performance benchmarks using benchmark.js."""
    path = Path(file_path)
    parsed = parse_js_functions(file_path)
    
    # Create benchmark script
    benchmark_code = f'''
const Benchmark = require('benchmark');
const module = require('{path.stem}');

const suite = new Benchmark.Suite();

'''
    
    for func in parsed.get("functions", []):
        func_name = func["name"]
        if not func_name.startswith("_"):
            benchmark_code += f'''
suite.add('{func_name}', () => {{
  module.{func_name}();
}});
'''
    
    benchmark_code += '''
suite
  .on('cycle', (event) => {
    console.log(String(event.target));
  })
  .on('complete', function() {
    const results = this.map(bench => ({
      name: bench.name,
      hz: bench.hz,
      stats: bench.stats
    }));
    console.log('---RESULTS---');
    console.log(JSON.stringify(results, null, 2));
  })
  .run({ async: true });
'''
    
    try:
        result = subprocess.run(
            ["node", "-e", benchmark_code],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=path.parent
        )
        
        output = result.stdout
        
        # Parse results
        results_match = re.search(r'---RESULTS---\n(.+)', output, re.DOTALL)
        benchmarks = []
        if results_match:
            try:
                benchmarks = json.loads(results_match.group(1))
            except:
                pass
        
        return {
            "success": result.returncode == 0,
            "benchmarks": benchmarks,
            "output": output
        }
        
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "output": ""
        }


def main():
    parser = argparse.ArgumentParser(description="JavaScript test runner")
    parser.add_argument("operation", choices=["generate", "run", "coverage", "mutation", "benchmark"])
    parser.add_argument("file_path")
    parser.add_argument("--framework", default="jest")
    parser.add_argument("--output")
    
    args = parser.parse_args()
    
    result = {}
    
    if args.operation == "generate":
        result = generate_jest_tests(args.file_path, args.output)
    elif args.operation == "run":
        result = run_jest_tests(args.file_path, args.framework)
    elif args.operation == "coverage":
        result = run_coverage(args.file_path, args.framework)
    elif args.operation == "mutation":
        result = run_mutation_test(args.file_path)
    elif args.operation == "benchmark":
        result = run_benchmark(args.file_path)
    
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
