#!/usr/bin/env python3
"""
Python test runner using pytest and coverage.py
Supports: generate, run, coverage, mutation, benchmark operations
"""

import argparse
import os
import sys
import subprocess
import json
import re
import ast
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def parse_function_signatures(file_path: str) -> List[Dict]:
    """Parse Python file to extract function/class signatures."""
    path = Path(file_path)
    if not path.exists():
        return []
    
    try:
        tree = ast.parse(path.read_text())
    except SyntaxError:
        return []
    
    functions = []
    classes = []
    
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.FunctionDef):
            args = []
            for arg in node.args.args:
                arg_type = ""
                if arg.annotation and isinstance(arg.annotation, ast.Name):
                    arg_type = f": {arg.annotation.id}"
                args.append(f"{arg.arg}{arg_type}")
            
            # Handle *args and **kwargs
            if node.args.vararg:
                args.append(f"*{node.args.vararg.arg}")
            if node.args.kwarg:
                args.append(f"**{node.args.kwarg.arg}")
            
            return_type = ""
            if node.returns and isinstance(node.returns, ast.Name):
                return_type = f" -> {node.returns.id}"
            
            functions.append({
                "name": node.name,
                "args": args,
                "return_type": return_type,
                "docstring": ast.get_docstring(node) or "",
                "lineno": node.lineno
            })
        
        elif isinstance(node, ast.ClassDef):
            methods = []
            for item in node.body:
                if isinstance(item, ast.FunctionDef):
                    if not item.name.startswith("_") or item.name == "__init__":
                        methods.append(item.name)
            
            classes.append({
                "name": node.name,
                "methods": methods,
                "docstring": ast.get_docstring(node) or "",
                "lineno": node.lineno
            })
    
    return {"functions": functions, "classes": classes}


def generate_pytest_tests(file_path: str, output_path: Optional[str] = None) -> Dict:
    """Generate pytest test scaffolding for a Python file."""
    path = Path(file_path)
    parsed = parse_function_signatures(file_path)
    
    module_name = path.stem
    test_file_name = f"test_{module_name}.py"
    
    if output_path:
        output = Path(output_path)
        if output.is_dir():
            test_file_path = output / test_file_name
        else:
            test_file_path = output
    else:
        test_file_path = path.parent / test_file_name
    
    lines = [
        f'"""',
        f'Tests for {path.name}',
        f'Auto-generated by test-automation skill',
        f'"""',
        f'',
        f'import pytest',
        f'from {module_name} import *',
        f'',
        f'',
    ]
    
    # Generate test functions
    for func in parsed.get("functions", []):
        if func["name"].startswith("_"):
            continue
        
        func_name = func["name"]
        docstring = func["docstring"][:50] + "..." if len(func["docstring"]) > 50 else func["docstring"]
        
        lines.extend([
            f'def test_{func_name}():',
            f'    """Test {func_name} function."""',
        ])
        
        if docstring:
            lines.append(f'    # {docstring}')
        
        # Generate test body based on args
        args_str = ", ".join([a.split(":")[0] for a in func["args"]])
        if args_str:
            lines.extend([
                f'    # Arrange',
                f'    # TODO: Set up test inputs for: {args_str}',
                f'   ',
                f'    # Act',
                f'    result = {func_name}({args_str})',
            ])
        else:
            lines.extend([
                f'    # Act',
                f'    result = {func_name}()',
            ])
        
        lines.extend([
            f'    ',
            f'    # Assert',
            f'    # TODO: Add appropriate assertions',
            f'    assert result is not None',
            f'',
        ])
    
    # Generate test classes
    for cls in parsed.get("classes", []):
        class_name = cls["name"]
        lines.extend([
            f'class Test{class_name}:',
            f'    """Tests for {class_name} class."""',
            f'    ',
            f'    def setup_method(self):',
            f'        """Set up test fixtures."""',
            f'        self.instance = {class_name}()',
            f'    ',
        ])
        
        for method in cls["methods"]:
            if method.startswith("_") and method != "__init__":
                continue
            
            test_method_name = method if method == "__init__" else f"test_{method}"
            lines.extend([
                f'    def {test_method_name}(self):',
                f'        """Test {method} method."""',
                f'        # TODO: Implement test',
                f'        pass',
                f'    ',
            ])
        
        lines.append('')
    
    # Add fixtures section
    lines.extend([
        f'',
        f'# Fixtures (add as needed)',
        f'# @pytest.fixture',
        f'# def sample_data():',
        f'#     return {{"key": "value"}}',
        f'',
    ])
    
    test_content = "\n".join(lines)
    
    # Write test file
    test_file_path.write_text(test_content)
    
    return {
        "success": True,
        "test_file": str(test_file_path),
        "functions_found": len(parsed.get("functions", [])),
        "classes_found": len(parsed.get("classes", [])),
        "output": f"Generated test file: {test_file_path}\n{test_content}"
    }


def run_pytest_tests(test_path: str) -> Dict:
    """Run pytest tests and return results."""
    path = Path(test_path)
    
    cmd = [sys.executable, "-m", "pytest", str(path), "-v", "--tb=short"]
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=300
        )
        
        # Parse pytest output
        output = result.stdout + result.stderr
        
        # Extract test summary
        passed = len(re.findall(r'PASSED', output))
        failed = len(re.findall(r'FAILED', output))
        errors = len(re.findall(r'ERROR', output))
        skipped = len(re.findall(r'SKIPPED', output))
        
        # Extract duration
        duration_match = re.search(r'(?:passed|failed|error).*?in ([\d.]+)s', output, re.IGNORECASE)
        duration = float(duration_match.group(1)) if duration_match else 0
        
        return {
            "success": result.returncode == 0,
            "exit_code": result.returncode,
            "passed": passed,
            "failed": failed,
            "errors": errors,
            "skipped": skipped,
            "duration_seconds": duration,
            "output": output
        }
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "error": "Test execution timed out (5 minutes)",
            "output": ""
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "output": ""
        }


def run_coverage(source_path: str) -> Dict:
    """Generate coverage report using coverage.py."""
    path = Path(source_path)
    
    # Determine project root
    if path.is_file():
        project_root = path.parent
    else:
        project_root = path
    
    # Find source package
    source_dirs = []
    for item in project_root.iterdir():
        if item.is_dir() and not item.name.startswith(".") and item.name not in ["tests", "test", "__pycache__", "venv", ".venv"]:
            if list(item.glob("*.py")):
                source_dirs.append(item.name)
    
    if not source_dirs:
        source_dirs = ["."]
    
    try:
        # Run coverage
        cov_cmd = [
            sys.executable, "-m", "coverage", "run",
            "--source", ",".join(source_dirs),
            "-m", "pytest", str(project_root)
        ]
        
        cov_result = subprocess.run(cov_cmd, capture_output=True, text=True, cwd=project_root)
        
        # Generate report
        report_cmd = [sys.executable, "-m", "coverage", "report", "--show-missing"]
        report_result = subprocess.run(report_cmd, capture_output=True, text=True, cwd=project_root)
        
        # Generate JSON report for parsing
        json_cmd = [sys.executable, "-m", "coverage", "json", "-o", "-"]
        json_result = subprocess.run(json_cmd, capture_output=True, text=True, cwd=project_root)
        
        coverage_data = {}
        try:
            if json_result.stdout:
                coverage_data = json.loads(json_result.stdout)
        except json.JSONDecodeError:
            pass
        
        # Parse text report
        report_output = report_result.stdout or report_result.stderr
        total_line = None
        for line in report_output.split("\n"):
            if line.strip().startswith("TOTAL"):
                total_line = line
                break
        
        coverage_percent = 0
        if coverage_data.get("totals", {}).get("percent_covered"):
            coverage_percent = coverage_data["totals"]["percent_covered"]
        elif total_line:
            match = re.search(r'(\d+)%', total_line)
            if match:
                coverage_percent = int(match.group(1))
        
        # Extract missing lines
        missing_lines = {}
        if coverage_data.get("files"):
            for filename, data in coverage_data["files"].items():
                if data.get("missing_lines"):
                    missing_lines[filename] = data["missing_lines"]
        
        return {
            "success": True,
            "coverage_percent": round(coverage_percent, 2),
            "missing_lines": missing_lines,
            "total_statements": coverage_data.get("totals", {}).get("covered_lines", 0) + coverage_data.get("totals", {}).get("missing_lines", 0),
            "covered_statements": coverage_data.get("totals", {}).get("covered_lines", 0),
            "output": report_output
        }
        
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "output": ""
        }


def run_mutation_test(file_path: str) -> Dict:
    """Run basic mutation testing using mutmut (if available) or custom implementation."""
    path = Path(file_path)
    
    # Check if mutmut is available
    try:
        result = subprocess.run([sys.executable, "-m", "mutmut", "--version"], 
                              capture_output=True, text=True, timeout=10)
        has_mutmut = result.returncode == 0
    except:
        has_mutmut = False
    
    if has_mutmut:
        # Run mutmut
        try:
            # First run tests to create baseline
            subprocess.run([sys.executable, "-m", "pytest", str(path.parent)], 
                         capture_output=True, cwd=path.parent)
            
            # Run mutation testing
            mut_result = subprocess.run(
                [sys.executable, "-m", "mutmut", "run", "--paths-to-mutate", str(path)],
                capture_output=True, text=True, timeout=300, cwd=path.parent
            )
            
            # Get results
            results = subprocess.run(
                [sys.executable, "-m", "mutmut", "results"],
                capture_output=True, text=True, cwd=path.parent
            )
            
            return {
                "success": True,
                "tool": "mutmut",
                "output": results.stdout or mut_result.stdout,
                "stderr": results.stderr or mut_result.stderr
            }
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    # Fallback: Simple mutation analysis
    # Perform basic mutation by modifying operators
    try:
        original_content = path.read_text()
        mutations = []
        
        # Simple mutations to test
        operators = [
            ("==", "!="),
            ("!=", "=="),
            (">", "<="),
            ("<", ">="),
            (">=", "<"),
            ("<=", ">"),
            ("True", "False"),
            ("False", "True"),
            ("and", "or"),
            ("or", "and"),
        ]
        
        killed = 0
        survived = 0
        
        for old_op, new_op in operators:
            if old_op in original_content:
                mutated = original_content.replace(old_op, new_op, 1)
                
                # Write mutation
                path.write_text(mutated)
                
                # Run tests
                test_result = subprocess.run(
                    [sys.executable, "-m", "pytest", str(path.parent), "-x"],
                    capture_output=True, text=True, timeout=60
                )
                
                if test_result.returncode != 0:
                    killed += 1
                    mutations.append({"operator": f"{old_op} -> {new_op}", "status": "killed"})
                else:
                    survived += 1
                    mutations.append({"operator": f"{old_op} -> {new_op}", "status": "survived"})
        
        # Restore original
        path.write_text(original_content)
        
        total = killed + survived
        score = (killed / total * 100) if total > 0 else 0
        
        return {
            "success": True,
            "tool": "basic",
            "mutations_tested": total,
            "killed": killed,
            "survived": survived,
            "mutation_score": round(score, 2),
            "mutations": mutations,
            "output": f"Mutation Score: {score:.1f}% ({killed}/{total} mutations killed)"
        }
        
    except Exception as e:
        # Ensure original is restored
        try:
            path.write_text(original_content)
        except:
            pass
        return {"success": False, "error": str(e)}


def run_benchmark(file_path: str) -> Dict:
    """Run performance benchmarks using pytest-benchmark or timeit."""
    path = Path(file_path)
    
    parsed = parse_function_signatures(file_path)
    functions = parsed.get("functions", [])
    
    if not functions:
        return {"success": False, "error": "No functions found to benchmark"}
    
    benchmarks = []
    
    # Create benchmark script
    bench_code = f'''
import timeit
import sys
sys.path.insert(0, "{path.parent}")
from {path.stem} import *

results = {{}}

'''
    
    for func in functions:
        if func["name"].startswith("_"):
            continue
        
        func_name = func["name"]
        args_str = ", ".join(["1"] * len(func["args"]))  # Simple dummy args
        
        bench_code += f'''
# Benchmark {func_name}
try:
    timer = timeit.Timer("{func_name}({args_str})", globals=globals())
    # Run once to check it works
    {func_name}({args_str})
    # Benchmark
    times = timer.repeat(number=1000, repeat=3)
    avg_time = sum(times) / len(times) / 1000 * 1000000  # microseconds per call
    results["{func_name}"] = {{"avg_us": avg_time, "min_us": min(times) / 1000 * 1000000}}
except Exception as e:
    results["{func_name}"] = {{"error": str(e)}}

'''
    
    bench_code += '''
import json
print(json.dumps(results))
'''
    
    try:
        result = subprocess.run(
            [sys.executable, "-c", bench_code],
            capture_output=True, text=True, timeout=60
        )
        
        if result.returncode == 0:
            benchmarks = json.loads(result.stdout)
        else:
            return {"success": False, "error": result.stderr, "output": result.stdout}
        
        # Format output
        output_lines = ["Performance Benchmarks:", "=" * 50]
        for func_name, data in benchmarks.items():
            if "error" in data:
                output_lines.append(f"{func_name}: Error - {data['error']}")
            else:
                output_lines.append(f"{func_name}: {data['avg_us']:.2f} µs/call (min: {data['min_us']:.2f} µs)")
        
        return {
            "success": True,
            "benchmarks": benchmarks,
            "output": "\n".join(output_lines)
        }
        
    except Exception as e:
        return {"success": False, "error": str(e)}


def main():
    parser = argparse.ArgumentParser(description="Python test runner")
    parser.add_argument("operation", choices=["generate", "run", "coverage", "mutation", "benchmark"])
    parser.add_argument("file_path")
    parser.add_argument("--framework", default="pytest")
    parser.add_argument("--output")
    
    args = parser.parse_args()
    
    result = {}
    
    if args.operation == "generate":
        result = generate_pytest_tests(args.file_path, args.output)
    elif args.operation == "run":
        result = run_pytest_tests(args.file_path)
    elif args.operation == "coverage":
        result = run_coverage(args.file_path)
    elif args.operation == "mutation":
        result = run_mutation_test(args.file_path)
    elif args.operation == "benchmark":
        result = run_benchmark(args.file_path)
    
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
